export const DICT = {
    'Bear': 'Медведь',
    'Cat': 'Кошка',
    'Roe_Deer': 'Косуля',
    'Moose': 'Лось',
    'Red_Deer': 'Олень',
    'Musk_Deer': 'Кабарга',
    'Wolf': 'Волк',
    'Marten': 'Куница',
    'Hare': 'Заяц',
    'Dog': 'Собака',
    'Mountain_Goat': 'Горный козел',
    'Badger': 'Барсук',
    'Fox': 'Лиса',
    'Snow_Leopard': 'Снежный барс',
    'Lynx': 'Рысь',
    'Wolverine': 'Росомаха',
    'Racoon_Dog': 'Енотовидная собака',
    'Squirrel': 'Белка',
    'Goral': 'Горал',
    'Tiger': 'Тигр',
    'Bison': 'Бизон'
} as Record<string, string>